name: testing
on:
  push:
    branches:
      - develop

jobs:

  update:
    runs-on: ubuntu-latest
    steps:
      - uses: nelonoel/branch-name@v1
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pymoo
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          curl -L http://github.com/msu-coinlab/pymoo/archive/${BRANCH_NAME}.zip --output pymoo.zip
          unzip -qq pymoo.zip
          pip install pymoo-${BRANCH_NAME}/
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get install pandoc rsync
      - name: Compile
        run: |
          make html
      - name: Upload
        uses: trendyminds/github-actions-rsync@master
        with:
          RSYNC_OPTIONS: -avzr --delete --exclude '*.ipynb'
          RSYNC_TARGET: /home/blankjul/pymoo.org/$(echo $GITHUB_REF | cut -d'/' -f 3)
          RSYNC_SOURCE: /doc/build/html/*
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_USERNAME: ${{secrets.SSH_USERNAME}}
          SSH_HOSTNAME: ${{secrets.SSH_HOSTNAME}}
