name: doc
on:
  push:
    branches:
      - master
      - release
      - develop

jobs:

  update:
    runs-on: ubuntu-latest
    steps:
      - uses: nelonoel/branch-name@v1.0.1
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Dependencies
        run: |
          sudo apt-get install pandoc rsync
          pip install -r requirements.txt
      - name: Install pymoo
        run: |
          python -m pip install --upgrade pip
          curl -L http://github.com/msu-coinlab/pymoo/archive/${BRANCH_NAME}.zip --output pymoo.zip
          unzip -qq pymoo.zip
          pip install pymoo-${BRANCH_NAME}/
      - name: Jupyter Config
        run: |
          echo "c = get_config()" >> ~/.ipython/profile_default/ipython_kernel_config.py
          echo "c.InlineBackend.figure_format = 'retina'" >> ~/.ipython/profile_default/ipython_kernel_config.py
          echo "c.InteractiveShellApp.matplotlib = 'inline'" >> ~/.ipython/profile_default/ipython_kernel_config.py
      - name: Compile
        run: |
          make html
      - name: Upload
        uses: trendyminds/github-actions-rsync@master
        with:
          RSYNC_OPTIONS: -avzr --delete --exclude '*.ipynb'
          RSYNC_TARGET: /home/blankjul/pymoo.org/${BRANCH_NAME}
          RSYNC_SOURCE: /build/html/*
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_USERNAME: ${{secrets.SSH_USERNAME}}
          SSH_HOSTNAME: ${{secrets.SSH_HOSTNAME}}
